name: ClearrIOS
options:
  bundleIdPrefix: com.mikeisesele
targets:
  ClearrIOS:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - path: Sources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.mikeisesele.clearr.ios
        INFOPLIST_FILE: Sources/Info.plist
        SWIFT_VERSION: 5.0
        PRODUCT_NAME: ClearrIOS
    dependencies:
      - framework: ../shared/build/xcode-frameworks/$(CONFIGURATION)/$(SDK_NAME)/shared.framework
        embed: true
    preBuildScripts:
      - name: Build Shared Framework
        basedOnDependencyAnalysis: false
        script: |
          cd "$SRCROOT/.."
          ./gradlew :shared:embedAndSignAppleFrameworkForXcode
